import { RESUME_TEMPLATES } from "@/components/(app)/general/templates/all-templates";
import { ResumeEditor } from "@/components/(app)/pages/(dashboard)/componenets/resumeeditor/resume-editor";
import { emptyResume } from "@/data/resume";
import type { Metadata } from "next";
import { notFound } from "next/navigation";

type PageProps = {
  params: Promise<{
    id: string;
  }>;
};

/**
 * The resume editor depends on the dynamic route parameter.
 * Allow this route to use runtime data instead of requiring
 * params to be available during prerendering.
 */
export const instant = false;

/**
 * --------------------------------------------------------------------------
 * METADATA
 * --------------------------------------------------------------------------
 */
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { id } = await params;

  const template = RESUME_TEMPLATES.find((template) => template.id === id);

  if (!template) {
    return {
      title: "Resume Editor | CVSTACKED",
      robots: {
        index: false,
        follow: false,
      },
    };
  }

  return {
    title: `Edit ${template.name} Resume | CVSTACKED`,
    description: `Create and customize your resume using the ${template.name} template on CVSTACKED.`,
    robots: {
      index: false,
      follow: false,
    },
  };
}

/**
 * --------------------------------------------------------------------------
 * PAGE
 * --------------------------------------------------------------------------
 *
 * URL:
 *
 * /app/resumes/new/tpl_7f3k9x2m
 *
 * The dynamic [id] here is ALWAYS the TEMPLATE ID.
 *
 * Example:
 *
 * tpl_7f3k9x2m
 *
 * It is NOT a database Resume.id.
 *
 * The real Resume.id will be generated by Prisma later when the user
 * clicks "Unlock PDF" and the API creates the Resume record.
 */
export default async function ResumeEditorPage({ params }: PageProps) {
  const { id } = await params;

  /**
   * ------------------------------------------------------------------------
   * FIND SELECTED TEMPLATE
   * ------------------------------------------------------------------------
   */
  const template = RESUME_TEMPLATES.find((template) => template.id === id);

  if (!template) {
    notFound();
  }

  /**
   * ------------------------------------------------------------------------
   * INITIAL EMPTY RESUME
   * ------------------------------------------------------------------------
   *
   * Start with empty user content.
   *
   * We intentionally do NOT use demo/sample resume data.
   *
   * The selected template information is attached to the editor so the
   * editor knows exactly which template the user is working with.
   */
  const initialResume = {
    ...emptyResume,

    /**
     * Selected template ID.
     *
     * Example:
     * tpl_7f3k9x2m
     */
    templateId: template.id,

    /**
     * Temporary client/editor identifier.
     *
     * IMPORTANT:
     * This is NOT the Prisma Resume.id.
     *
     * The real database Resume.id will be generated by Prisma when the
     * Unlock PDF API creates the Resume.
     */
    id: `draft-${template.id}`,

    /**
     * Default title for the editor.
     *
     * The user can change this later.
     */
    title: "My Resume",
  };

  return (
    <ResumeEditor
      initialResume={initialResume}
      templateId={template.id}
      templateName={template.name}
      templateDescription={template.description}
      templateCategory={template.category}
      templatePlan={template.plan}
    />
  );
}
